//Recreate game of rock, paper, scissors

//Requirements___
//2 inputs Player 1 && Player 2 -> Choose at the same time.
//rock beats scissors, scissors beats paper, and paper beats rock
//If both inputs are equal then game ends as draw.

// rock === 1; paper === 2; scissors === 3 maybe

//Further Exploration___
//Have computer select a play instead of a player
//Expand rules to allow 3 players

//Code